# yamllint disable rule:truthy
---
name: Sync Google Sheets (API)

on:
  workflow_dispatch: {}  # yamllint disable-line truthy
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      SHEET_TABS: 1,2,3,4,5
      OUTPUT_DIR: data
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install --upgrade google-api-python-client google-auth
      - name: Run sync
        run: python3 tools/update_sheets.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update data from Google Sheets API'
