name: Sync Google Sheet

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Update JSON files
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_TABS: "1,2,3,4,5"
          OUTPUT_DIR: data
          # HTTP_PROXY: ${{ vars.HTTP_PROXY }}
          # HTTPS_PROXY: ${{ vars.HTTPS_PROXY }}
        run: python3 tools/update_sheets.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(data): sync sheets'
