name: Update sheets

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-sheets
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run update_sheets.py
        env:
          SHEET_ID: '1Dc01H5hAxPwwhyY_GnRAVFP2-uINanwJS1jhtFs2syU'
          SHEET_TABS: '1,2,3,4,5'
          OUTPUT_DIR: 'data'
        run: python tools/update_sheets.py
      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data
            git commit -m "chore(data): refresh sheets [skip ci]"
            git push
          else
            echo "No changes to commit"
