# yamllint disable rule:truthy
---
name: Sync Events Sheet

on:
  workflow_dispatch: {}  # yamllint disable-line truthy
  schedule:
    - cron: '0 */8 * * *'

permissions:
  contents: write
  
jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      AGENDA_ID: ${{ secrets.AGENDA_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      AGENDA_TABS: 1
      OUTPUT_DIR: data      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install --upgrade google-api-python-client google-auth          
      - name: Run sync
        run: python3 tools/update_events.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update events from Google Sheet'
