name: Update JSON files

on:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: refresh-jsons
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run update scripts
        env:
          AGENDA_SHEET_ID: "1IkA50UI7OpFd_VYUb5kNe9V0jj-MZKqu"
        run: |
          python tools/update_classificacions.py
          python tools/update_ranquing.py
          python tools/update_events.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add classificacions.json ranquing.json events.json
            git commit -m "chore(data): refresh JSON files [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
