name: Update enllacos

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-enllacos
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run update_enllacos.py
        env:
          SHEETS_ID: '11OYEE5abd8l5jrgJRcSOmvzE5vhYJCgkBIJpgEPS43k'
          SHEETS_TAB: '1'
          OUTPUT_FILE: 'data/enllacos.json'
        run: python tools/update_enllacos.py
      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/enllacos.json
            git commit -m "chore(data): refresh enllacos [skip ci]"
            git push
          else
            echo "No changes to commit"
