# yamllint disable rule:truthy
---
name: Sync Ranquing Sheet (API)

on:
  workflow_dispatch: {}  # yamllint disable-line truthy
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      RANK_ID: ${{ secrets.RANK_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      RANK_TAB: 1
      OUTPUT_FILE: data/ranquing.json
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install --upgrade google-api-python-client google-auth
      - name: Run sync
        run: python3 tools/update_ranquing.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update links from Google Sheets API'

          
