name: Update ranquing

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-ranquing
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run update_ranquing.py
        env:
          RANK_ID: ${{ vars.RANK_ID }}
          RANK_TAB: '1'
          OUTPUT_FILE: 'data/ranquing.json'
        run: python tools/update_ranquing.py
      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/ranquing.json
            git commit -m "chore(data): refresh ranquing [skip ci]"
            git push
          else
            echo "No changes to commit"
