name: Update events

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-events
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run update_events.py
        env:
          AGENDA_ID: '1IkA50UI7OpFd_VYUb5kNe9V0jj-MZKqu'
          AGENDA_TAB: '1'
          OUTPUT_FILE: 'data/events.json'
        run: python tools/update_events.py
      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/events.json
            git commit -m "chore(data): refresh events [skip ci]"
            git push
          else
            echo "No changes to commit"
